/*
 * AWS Migration Hub
 * <p>The AWS Migration Hub API methods help to obtain server and application migration status and integrate your resource-specific migration tool by providing a programmatic interface to Migration Hub.</p> <p>Remember that you must set your AWS Migration Hub home region before you call any of these APIs, or a <code>HomeRegionNotSetException</code> error will be returned. Also, you must make the API calls while in your home region.</p>
 *
 * The version of the OpenAPI document: 2017-05-31
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DisassociateCreatedArtifactRequest
 */
public class DisassociateCreatedArtifactRequestTest {
    private final DisassociateCreatedArtifactRequest model = new DisassociateCreatedArtifactRequest();

    /**
     * Model tests for DisassociateCreatedArtifactRequest
     */
    @Test
    public void testDisassociateCreatedArtifactRequest() {
        // TODO: test DisassociateCreatedArtifactRequest
    }

    /**
     * Test the property 'progressUpdateStream'
     */
    @Test
    public void progressUpdateStreamTest() {
        // TODO: test progressUpdateStream
    }

    /**
     * Test the property 'migrationTaskName'
     */
    @Test
    public void migrationTaskNameTest() {
        // TODO: test migrationTaskName
    }

    /**
     * Test the property 'createdArtifactName'
     */
    @Test
    public void createdArtifactNameTest() {
        // TODO: test createdArtifactName
    }

    /**
     * Test the property 'dryRun'
     */
    @Test
    public void dryRunTest() {
        // TODO: test dryRun
    }

}
