/*
 * AWS Migration Hub
 * <p>The AWS Migration Hub API methods help to obtain server and application migration status and integrate your resource-specific migration tool by providing a programmatic interface to Migration Hub.</p> <p>Remember that you must set your AWS Migration Hub home region before you call any of these APIs, or a <code>HomeRegionNotSetException</code> error will be returned. Also, you must make the API calls while in your home region.</p>
 *
 * The version of the OpenAPI document: 2017-05-31
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ListProgressUpdateStreamsResult
 */
public class ListProgressUpdateStreamsResultTest {
    private final ListProgressUpdateStreamsResult model = new ListProgressUpdateStreamsResult();

    /**
     * Model tests for ListProgressUpdateStreamsResult
     */
    @Test
    public void testListProgressUpdateStreamsResult() {
        // TODO: test ListProgressUpdateStreamsResult
    }

    /**
     * Test the property 'progressUpdateStreamSummaryList'
     */
    @Test
    public void progressUpdateStreamSummaryListTest() {
        // TODO: test progressUpdateStreamSummaryList
    }

    /**
     * Test the property 'nextToken'
     */
    @Test
    public void nextTokenTest() {
        // TODO: test nextToken
    }

}
