/*
 * AWS Migration Hub
 * <p>The AWS Migration Hub API methods help to obtain server and application migration status and integrate your resource-specific migration tool by providing a programmatic interface to Migration Hub.</p> <p>Remember that you must set your AWS Migration Hub home region before you call any of these APIs, or a <code>HomeRegionNotSetException</code> error will be returned. Also, you must make the API calls while in your home region.</p>
 *
 * The version of the OpenAPI document: 2017-05-31
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ListCreatedArtifactsRequest
 */
public class ListCreatedArtifactsRequestTest {
    private final ListCreatedArtifactsRequest model = new ListCreatedArtifactsRequest();

    /**
     * Model tests for ListCreatedArtifactsRequest
     */
    @Test
    public void testListCreatedArtifactsRequest() {
        // TODO: test ListCreatedArtifactsRequest
    }

    /**
     * Test the property 'progressUpdateStream'
     */
    @Test
    public void progressUpdateStreamTest() {
        // TODO: test progressUpdateStream
    }

    /**
     * Test the property 'migrationTaskName'
     */
    @Test
    public void migrationTaskNameTest() {
        // TODO: test migrationTaskName
    }

    /**
     * Test the property 'nextToken'
     */
    @Test
    public void nextTokenTest() {
        // TODO: test nextToken
    }

    /**
     * Test the property 'maxResults'
     */
    @Test
    public void maxResultsTest() {
        // TODO: test maxResults
    }

}
