/*
 * AWS Migration Hub
 * <p>The AWS Migration Hub API methods help to obtain server and application migration status and integrate your resource-specific migration tool by providing a programmatic interface to Migration Hub.</p> <p>Remember that you must set your AWS Migration Hub home region before you call any of these APIs, or a <code>HomeRegionNotSetException</code> error will be returned. Also, you must make the API calls while in your home region.</p>
 *
 * The version of the OpenAPI document: 2017-05-31
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.MigrationTaskTask;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MigrationTask
 */
public class MigrationTaskTest {
    private final MigrationTask model = new MigrationTask();

    /**
     * Model tests for MigrationTask
     */
    @Test
    public void testMigrationTask() {
        // TODO: test MigrationTask
    }

    /**
     * Test the property 'progressUpdateStream'
     */
    @Test
    public void progressUpdateStreamTest() {
        // TODO: test progressUpdateStream
    }

    /**
     * Test the property 'migrationTaskName'
     */
    @Test
    public void migrationTaskNameTest() {
        // TODO: test migrationTaskName
    }

    /**
     * Test the property 'task'
     */
    @Test
    public void taskTest() {
        // TODO: test task
    }

    /**
     * Test the property 'updateDateTime'
     */
    @Test
    public void updateDateTimeTest() {
        // TODO: test updateDateTime
    }

    /**
     * Test the property 'resourceAttributeList'
     */
    @Test
    public void resourceAttributeListTest() {
        // TODO: test resourceAttributeList
    }

}
