package main

import (
	"github.com/aws-migration-hub/mcp-server/config"
	"github.com/aws-migration-hub/mcp-server/models"
	tools_x_amz_target_awsmigrationhub_notifyapplicationstate "github.com/aws-migration-hub/mcp-server/tools/x_amz_target_awsmigrationhub_notifyapplicationstate"
	tools_x_amz_target_awsmigrationhub_disassociatediscoveredresource "github.com/aws-migration-hub/mcp-server/tools/x_amz_target_awsmigrationhub_disassociatediscoveredresource"
	tools_x_amz_target_awsmigrationhub_disassociatecreatedartifact "github.com/aws-migration-hub/mcp-server/tools/x_amz_target_awsmigrationhub_disassociatecreatedartifact"
	tools_x_amz_target_awsmigrationhub_deleteprogressupdatestream "github.com/aws-migration-hub/mcp-server/tools/x_amz_target_awsmigrationhub_deleteprogressupdatestream"
	tools_x_amz_target_awsmigrationhub_associatecreatedartifact "github.com/aws-migration-hub/mcp-server/tools/x_amz_target_awsmigrationhub_associatecreatedartifact"
	tools_x_amz_target_awsmigrationhub_notifymigrationtaskstate "github.com/aws-migration-hub/mcp-server/tools/x_amz_target_awsmigrationhub_notifymigrationtaskstate"
	tools_x_amz_target_awsmigrationhub_associatediscoveredresource "github.com/aws-migration-hub/mcp-server/tools/x_amz_target_awsmigrationhub_associatediscoveredresource"
	tools_x_amz_target_awsmigrationhub_createprogressupdatestream "github.com/aws-migration-hub/mcp-server/tools/x_amz_target_awsmigrationhub_createprogressupdatestream"
	tools_x_amz_target_awsmigrationhub_describeapplicationstate "github.com/aws-migration-hub/mcp-server/tools/x_amz_target_awsmigrationhub_describeapplicationstate"
	tools_x_amz_target_awsmigrationhub_listdiscoveredresources "github.com/aws-migration-hub/mcp-server/tools/x_amz_target_awsmigrationhub_listdiscoveredresources"
	tools_x_amz_target_awsmigrationhub_putresourceattributes "github.com/aws-migration-hub/mcp-server/tools/x_amz_target_awsmigrationhub_putresourceattributes"
	tools_x_amz_target_awsmigrationhub_listmigrationtasks "github.com/aws-migration-hub/mcp-server/tools/x_amz_target_awsmigrationhub_listmigrationtasks"
	tools_x_amz_target_awsmigrationhub_listapplicationstates "github.com/aws-migration-hub/mcp-server/tools/x_amz_target_awsmigrationhub_listapplicationstates"
	tools_x_amz_target_awsmigrationhub_listprogressupdatestreams "github.com/aws-migration-hub/mcp-server/tools/x_amz_target_awsmigrationhub_listprogressupdatestreams"
	tools_x_amz_target_awsmigrationhub_describemigrationtask "github.com/aws-migration-hub/mcp-server/tools/x_amz_target_awsmigrationhub_describemigrationtask"
	tools_x_amz_target_awsmigrationhub_listcreatedartifacts "github.com/aws-migration-hub/mcp-server/tools/x_amz_target_awsmigrationhub_listcreatedartifacts"
	tools_x_amz_target_awsmigrationhub_importmigrationtask "github.com/aws-migration-hub/mcp-server/tools/x_amz_target_awsmigrationhub_importmigrationtask"
)

func GetAll(cfg *config.APIConfig) []models.Tool {
	return []models.Tool{
		tools_x_amz_target_awsmigrationhub_notifyapplicationstate.CreateNotifyapplicationstateTool(cfg),
		tools_x_amz_target_awsmigrationhub_disassociatediscoveredresource.CreateDisassociatediscoveredresourceTool(cfg),
		tools_x_amz_target_awsmigrationhub_disassociatecreatedartifact.CreateDisassociatecreatedartifactTool(cfg),
		tools_x_amz_target_awsmigrationhub_deleteprogressupdatestream.CreateDeleteprogressupdatestreamTool(cfg),
		tools_x_amz_target_awsmigrationhub_associatecreatedartifact.CreateAssociatecreatedartifactTool(cfg),
		tools_x_amz_target_awsmigrationhub_notifymigrationtaskstate.CreateNotifymigrationtaskstateTool(cfg),
		tools_x_amz_target_awsmigrationhub_associatediscoveredresource.CreateAssociatediscoveredresourceTool(cfg),
		tools_x_amz_target_awsmigrationhub_createprogressupdatestream.CreateCreateprogressupdatestreamTool(cfg),
		tools_x_amz_target_awsmigrationhub_describeapplicationstate.CreateDescribeapplicationstateTool(cfg),
		tools_x_amz_target_awsmigrationhub_listdiscoveredresources.CreateListdiscoveredresourcesTool(cfg),
		tools_x_amz_target_awsmigrationhub_putresourceattributes.CreatePutresourceattributesTool(cfg),
		tools_x_amz_target_awsmigrationhub_listmigrationtasks.CreateListmigrationtasksTool(cfg),
		tools_x_amz_target_awsmigrationhub_listapplicationstates.CreateListapplicationstatesTool(cfg),
		tools_x_amz_target_awsmigrationhub_listprogressupdatestreams.CreateListprogressupdatestreamsTool(cfg),
		tools_x_amz_target_awsmigrationhub_describemigrationtask.CreateDescribemigrationtaskTool(cfg),
		tools_x_amz_target_awsmigrationhub_listcreatedartifacts.CreateListcreatedartifactsTool(cfg),
		tools_x_amz_target_awsmigrationhub_importmigrationtask.CreateImportmigrationtaskTool(cfg),
	}
}
