/*
 * AWS Migration Hub
 * <p>The AWS Migration Hub API methods help to obtain server and application migration status and integrate your resource-specific migration tool by providing a programmatic interface to Migration Hub.</p> <p>Remember that you must set your AWS Migration Hub home region before you call any of these APIs, or a <code>HomeRegionNotSetException</code> error will be returned. Also, you must make the API calls while in your home region.</p>
 *
 * The version of the OpenAPI document: 2017-05-31
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.AssociateDiscoveredResourceRequestDiscoveredResource;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * AssociateDiscoveredResourceRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:02:31.467047+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class AssociateDiscoveredResourceRequest {
  public static final String SERIALIZED_NAME_PROGRESS_UPDATE_STREAM = "ProgressUpdateStream";
  @SerializedName(SERIALIZED_NAME_PROGRESS_UPDATE_STREAM)
  @javax.annotation.Nonnull
  private String progressUpdateStream;

  public static final String SERIALIZED_NAME_MIGRATION_TASK_NAME = "MigrationTaskName";
  @SerializedName(SERIALIZED_NAME_MIGRATION_TASK_NAME)
  @javax.annotation.Nonnull
  private String migrationTaskName;

  public static final String SERIALIZED_NAME_DISCOVERED_RESOURCE = "DiscoveredResource";
  @SerializedName(SERIALIZED_NAME_DISCOVERED_RESOURCE)
  @javax.annotation.Nonnull
  private AssociateDiscoveredResourceRequestDiscoveredResource discoveredResource;

  public static final String SERIALIZED_NAME_DRY_RUN = "DryRun";
  @SerializedName(SERIALIZED_NAME_DRY_RUN)
  @javax.annotation.Nullable
  private Boolean dryRun;

  public AssociateDiscoveredResourceRequest() {
  }

  public AssociateDiscoveredResourceRequest progressUpdateStream(@javax.annotation.Nonnull String progressUpdateStream) {
    this.progressUpdateStream = progressUpdateStream;
    return this;
  }

  /**
   * Get progressUpdateStream
   * @return progressUpdateStream
   */
  @javax.annotation.Nonnull
  public String getProgressUpdateStream() {
    return progressUpdateStream;
  }

  public void setProgressUpdateStream(@javax.annotation.Nonnull String progressUpdateStream) {
    this.progressUpdateStream = progressUpdateStream;
  }


  public AssociateDiscoveredResourceRequest migrationTaskName(@javax.annotation.Nonnull String migrationTaskName) {
    this.migrationTaskName = migrationTaskName;
    return this;
  }

  /**
   * Get migrationTaskName
   * @return migrationTaskName
   */
  @javax.annotation.Nonnull
  public String getMigrationTaskName() {
    return migrationTaskName;
  }

  public void setMigrationTaskName(@javax.annotation.Nonnull String migrationTaskName) {
    this.migrationTaskName = migrationTaskName;
  }


  public AssociateDiscoveredResourceRequest discoveredResource(@javax.annotation.Nonnull AssociateDiscoveredResourceRequestDiscoveredResource discoveredResource) {
    this.discoveredResource = discoveredResource;
    return this;
  }

  /**
   * Get discoveredResource
   * @return discoveredResource
   */
  @javax.annotation.Nonnull
  public AssociateDiscoveredResourceRequestDiscoveredResource getDiscoveredResource() {
    return discoveredResource;
  }

  public void setDiscoveredResource(@javax.annotation.Nonnull AssociateDiscoveredResourceRequestDiscoveredResource discoveredResource) {
    this.discoveredResource = discoveredResource;
  }


  public AssociateDiscoveredResourceRequest dryRun(@javax.annotation.Nullable Boolean dryRun) {
    this.dryRun = dryRun;
    return this;
  }

  /**
   * Get dryRun
   * @return dryRun
   */
  @javax.annotation.Nullable
  public Boolean getDryRun() {
    return dryRun;
  }

  public void setDryRun(@javax.annotation.Nullable Boolean dryRun) {
    this.dryRun = dryRun;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssociateDiscoveredResourceRequest associateDiscoveredResourceRequest = (AssociateDiscoveredResourceRequest) o;
    return Objects.equals(this.progressUpdateStream, associateDiscoveredResourceRequest.progressUpdateStream) &&
        Objects.equals(this.migrationTaskName, associateDiscoveredResourceRequest.migrationTaskName) &&
        Objects.equals(this.discoveredResource, associateDiscoveredResourceRequest.discoveredResource) &&
        Objects.equals(this.dryRun, associateDiscoveredResourceRequest.dryRun);
  }

  @Override
  public int hashCode() {
    return Objects.hash(progressUpdateStream, migrationTaskName, discoveredResource, dryRun);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssociateDiscoveredResourceRequest {\n");
    sb.append("    progressUpdateStream: ").append(toIndentedString(progressUpdateStream)).append("\n");
    sb.append("    migrationTaskName: ").append(toIndentedString(migrationTaskName)).append("\n");
    sb.append("    discoveredResource: ").append(toIndentedString(discoveredResource)).append("\n");
    sb.append("    dryRun: ").append(toIndentedString(dryRun)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("ProgressUpdateStream");
    openapiFields.add("MigrationTaskName");
    openapiFields.add("DiscoveredResource");
    openapiFields.add("DryRun");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("ProgressUpdateStream");
    openapiRequiredFields.add("MigrationTaskName");
    openapiRequiredFields.add("DiscoveredResource");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AssociateDiscoveredResourceRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AssociateDiscoveredResourceRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AssociateDiscoveredResourceRequest is not found in the empty JSON string", AssociateDiscoveredResourceRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AssociateDiscoveredResourceRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AssociateDiscoveredResourceRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AssociateDiscoveredResourceRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `ProgressUpdateStream`
      String.validateJsonElement(jsonObj.get("ProgressUpdateStream"));
      // validate the required field `MigrationTaskName`
      String.validateJsonElement(jsonObj.get("MigrationTaskName"));
      // validate the required field `DiscoveredResource`
      AssociateDiscoveredResourceRequestDiscoveredResource.validateJsonElement(jsonObj.get("DiscoveredResource"));
      // validate the optional field `DryRun`
      if (jsonObj.get("DryRun") != null && !jsonObj.get("DryRun").isJsonNull()) {
        Boolean.validateJsonElement(jsonObj.get("DryRun"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AssociateDiscoveredResourceRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AssociateDiscoveredResourceRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AssociateDiscoveredResourceRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AssociateDiscoveredResourceRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<AssociateDiscoveredResourceRequest>() {
           @Override
           public void write(JsonWriter out, AssociateDiscoveredResourceRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AssociateDiscoveredResourceRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AssociateDiscoveredResourceRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AssociateDiscoveredResourceRequest
   * @throws IOException if the JSON string is invalid with respect to AssociateDiscoveredResourceRequest
   */
  public static AssociateDiscoveredResourceRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AssociateDiscoveredResourceRequest.class);
  }

  /**
   * Convert an instance of AssociateDiscoveredResourceRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

