/*
 * AWS Migration Hub
 * <p>The AWS Migration Hub API methods help to obtain server and application migration status and integrate your resource-specific migration tool by providing a programmatic interface to Migration Hub.</p> <p>Remember that you must set your AWS Migration Hub home region before you call any of these APIs, or a <code>HomeRegionNotSetException</code> error will be returned. Also, you must make the API calls while in your home region.</p>
 *
 * The version of the OpenAPI document: 2017-05-31
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * DeleteProgressUpdateStreamRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:02:31.467047+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class DeleteProgressUpdateStreamRequest {
  public static final String SERIALIZED_NAME_PROGRESS_UPDATE_STREAM_NAME = "ProgressUpdateStreamName";
  @SerializedName(SERIALIZED_NAME_PROGRESS_UPDATE_STREAM_NAME)
  @javax.annotation.Nonnull
  private String progressUpdateStreamName;

  public static final String SERIALIZED_NAME_DRY_RUN = "DryRun";
  @SerializedName(SERIALIZED_NAME_DRY_RUN)
  @javax.annotation.Nullable
  private Boolean dryRun;

  public DeleteProgressUpdateStreamRequest() {
  }

  public DeleteProgressUpdateStreamRequest progressUpdateStreamName(@javax.annotation.Nonnull String progressUpdateStreamName) {
    this.progressUpdateStreamName = progressUpdateStreamName;
    return this;
  }

  /**
   * Get progressUpdateStreamName
   * @return progressUpdateStreamName
   */
  @javax.annotation.Nonnull
  public String getProgressUpdateStreamName() {
    return progressUpdateStreamName;
  }

  public void setProgressUpdateStreamName(@javax.annotation.Nonnull String progressUpdateStreamName) {
    this.progressUpdateStreamName = progressUpdateStreamName;
  }


  public DeleteProgressUpdateStreamRequest dryRun(@javax.annotation.Nullable Boolean dryRun) {
    this.dryRun = dryRun;
    return this;
  }

  /**
   * Get dryRun
   * @return dryRun
   */
  @javax.annotation.Nullable
  public Boolean getDryRun() {
    return dryRun;
  }

  public void setDryRun(@javax.annotation.Nullable Boolean dryRun) {
    this.dryRun = dryRun;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeleteProgressUpdateStreamRequest deleteProgressUpdateStreamRequest = (DeleteProgressUpdateStreamRequest) o;
    return Objects.equals(this.progressUpdateStreamName, deleteProgressUpdateStreamRequest.progressUpdateStreamName) &&
        Objects.equals(this.dryRun, deleteProgressUpdateStreamRequest.dryRun);
  }

  @Override
  public int hashCode() {
    return Objects.hash(progressUpdateStreamName, dryRun);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeleteProgressUpdateStreamRequest {\n");
    sb.append("    progressUpdateStreamName: ").append(toIndentedString(progressUpdateStreamName)).append("\n");
    sb.append("    dryRun: ").append(toIndentedString(dryRun)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("ProgressUpdateStreamName");
    openapiFields.add("DryRun");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("ProgressUpdateStreamName");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DeleteProgressUpdateStreamRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DeleteProgressUpdateStreamRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DeleteProgressUpdateStreamRequest is not found in the empty JSON string", DeleteProgressUpdateStreamRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DeleteProgressUpdateStreamRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DeleteProgressUpdateStreamRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : DeleteProgressUpdateStreamRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `ProgressUpdateStreamName`
      String.validateJsonElement(jsonObj.get("ProgressUpdateStreamName"));
      // validate the optional field `DryRun`
      if (jsonObj.get("DryRun") != null && !jsonObj.get("DryRun").isJsonNull()) {
        Boolean.validateJsonElement(jsonObj.get("DryRun"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DeleteProgressUpdateStreamRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DeleteProgressUpdateStreamRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DeleteProgressUpdateStreamRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DeleteProgressUpdateStreamRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<DeleteProgressUpdateStreamRequest>() {
           @Override
           public void write(JsonWriter out, DeleteProgressUpdateStreamRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DeleteProgressUpdateStreamRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DeleteProgressUpdateStreamRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DeleteProgressUpdateStreamRequest
   * @throws IOException if the JSON string is invalid with respect to DeleteProgressUpdateStreamRequest
   */
  public static DeleteProgressUpdateStreamRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DeleteProgressUpdateStreamRequest.class);
  }

  /**
   * Convert an instance of DeleteProgressUpdateStreamRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

