/*
 * AWS Migration Hub
 * <p>The AWS Migration Hub API methods help to obtain server and application migration status and integrate your resource-specific migration tool by providing a programmatic interface to Migration Hub.</p> <p>Remember that you must set your AWS Migration Hub home region before you call any of these APIs, or a <code>HomeRegionNotSetException</code> error will be returned. Also, you must make the API calls while in your home region.</p>
 *
 * The version of the OpenAPI document: 2017-05-31
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.DescribeMigrationTaskResultMigrationTask;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * DescribeMigrationTaskResult
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:02:31.467047+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class DescribeMigrationTaskResult {
  public static final String SERIALIZED_NAME_MIGRATION_TASK = "MigrationTask";
  @SerializedName(SERIALIZED_NAME_MIGRATION_TASK)
  @javax.annotation.Nullable
  private DescribeMigrationTaskResultMigrationTask migrationTask;

  public DescribeMigrationTaskResult() {
  }

  public DescribeMigrationTaskResult migrationTask(@javax.annotation.Nullable DescribeMigrationTaskResultMigrationTask migrationTask) {
    this.migrationTask = migrationTask;
    return this;
  }

  /**
   * Get migrationTask
   * @return migrationTask
   */
  @javax.annotation.Nullable
  public DescribeMigrationTaskResultMigrationTask getMigrationTask() {
    return migrationTask;
  }

  public void setMigrationTask(@javax.annotation.Nullable DescribeMigrationTaskResultMigrationTask migrationTask) {
    this.migrationTask = migrationTask;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DescribeMigrationTaskResult describeMigrationTaskResult = (DescribeMigrationTaskResult) o;
    return Objects.equals(this.migrationTask, describeMigrationTaskResult.migrationTask);
  }

  @Override
  public int hashCode() {
    return Objects.hash(migrationTask);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DescribeMigrationTaskResult {\n");
    sb.append("    migrationTask: ").append(toIndentedString(migrationTask)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("MigrationTask");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DescribeMigrationTaskResult
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DescribeMigrationTaskResult.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DescribeMigrationTaskResult is not found in the empty JSON string", DescribeMigrationTaskResult.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DescribeMigrationTaskResult.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DescribeMigrationTaskResult` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `MigrationTask`
      if (jsonObj.get("MigrationTask") != null && !jsonObj.get("MigrationTask").isJsonNull()) {
        DescribeMigrationTaskResultMigrationTask.validateJsonElement(jsonObj.get("MigrationTask"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DescribeMigrationTaskResult.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DescribeMigrationTaskResult' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DescribeMigrationTaskResult> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DescribeMigrationTaskResult.class));

       return (TypeAdapter<T>) new TypeAdapter<DescribeMigrationTaskResult>() {
           @Override
           public void write(JsonWriter out, DescribeMigrationTaskResult value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DescribeMigrationTaskResult read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DescribeMigrationTaskResult given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DescribeMigrationTaskResult
   * @throws IOException if the JSON string is invalid with respect to DescribeMigrationTaskResult
   */
  public static DescribeMigrationTaskResult fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DescribeMigrationTaskResult.class);
  }

  /**
   * Convert an instance of DescribeMigrationTaskResult to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

