/*
 * AWS Migration Hub
 * <p>The AWS Migration Hub API methods help to obtain server and application migration status and integrate your resource-specific migration tool by providing a programmatic interface to Migration Hub.</p> <p>Remember that you must set your AWS Migration Hub home region before you call any of these APIs, or a <code>HomeRegionNotSetException</code> error will be returned. Also, you must make the API calls while in your home region.</p>
 *
 * The version of the OpenAPI document: 2017-05-31
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.MigrationTaskTask;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * DescribeMigrationTaskResultMigrationTask
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:02:31.467047+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class DescribeMigrationTaskResultMigrationTask {
  public static final String SERIALIZED_NAME_PROGRESS_UPDATE_STREAM = "ProgressUpdateStream";
  @SerializedName(SERIALIZED_NAME_PROGRESS_UPDATE_STREAM)
  @javax.annotation.Nullable
  private String progressUpdateStream;

  public static final String SERIALIZED_NAME_MIGRATION_TASK_NAME = "MigrationTaskName";
  @SerializedName(SERIALIZED_NAME_MIGRATION_TASK_NAME)
  @javax.annotation.Nullable
  private String migrationTaskName;

  public static final String SERIALIZED_NAME_TASK = "Task";
  @SerializedName(SERIALIZED_NAME_TASK)
  @javax.annotation.Nullable
  private MigrationTaskTask task;

  public static final String SERIALIZED_NAME_UPDATE_DATE_TIME = "UpdateDateTime";
  @SerializedName(SERIALIZED_NAME_UPDATE_DATE_TIME)
  @javax.annotation.Nullable
  private OffsetDateTime updateDateTime;

  public static final String SERIALIZED_NAME_RESOURCE_ATTRIBUTE_LIST = "ResourceAttributeList";
  @SerializedName(SERIALIZED_NAME_RESOURCE_ATTRIBUTE_LIST)
  @javax.annotation.Nullable
  private List resourceAttributeList;

  public DescribeMigrationTaskResultMigrationTask() {
  }

  public DescribeMigrationTaskResultMigrationTask progressUpdateStream(@javax.annotation.Nullable String progressUpdateStream) {
    this.progressUpdateStream = progressUpdateStream;
    return this;
  }

  /**
   * Get progressUpdateStream
   * @return progressUpdateStream
   */
  @javax.annotation.Nullable
  public String getProgressUpdateStream() {
    return progressUpdateStream;
  }

  public void setProgressUpdateStream(@javax.annotation.Nullable String progressUpdateStream) {
    this.progressUpdateStream = progressUpdateStream;
  }


  public DescribeMigrationTaskResultMigrationTask migrationTaskName(@javax.annotation.Nullable String migrationTaskName) {
    this.migrationTaskName = migrationTaskName;
    return this;
  }

  /**
   * Get migrationTaskName
   * @return migrationTaskName
   */
  @javax.annotation.Nullable
  public String getMigrationTaskName() {
    return migrationTaskName;
  }

  public void setMigrationTaskName(@javax.annotation.Nullable String migrationTaskName) {
    this.migrationTaskName = migrationTaskName;
  }


  public DescribeMigrationTaskResultMigrationTask task(@javax.annotation.Nullable MigrationTaskTask task) {
    this.task = task;
    return this;
  }

  /**
   * Get task
   * @return task
   */
  @javax.annotation.Nullable
  public MigrationTaskTask getTask() {
    return task;
  }

  public void setTask(@javax.annotation.Nullable MigrationTaskTask task) {
    this.task = task;
  }


  public DescribeMigrationTaskResultMigrationTask updateDateTime(@javax.annotation.Nullable OffsetDateTime updateDateTime) {
    this.updateDateTime = updateDateTime;
    return this;
  }

  /**
   * Get updateDateTime
   * @return updateDateTime
   */
  @javax.annotation.Nullable
  public OffsetDateTime getUpdateDateTime() {
    return updateDateTime;
  }

  public void setUpdateDateTime(@javax.annotation.Nullable OffsetDateTime updateDateTime) {
    this.updateDateTime = updateDateTime;
  }


  public DescribeMigrationTaskResultMigrationTask resourceAttributeList(@javax.annotation.Nullable List resourceAttributeList) {
    this.resourceAttributeList = resourceAttributeList;
    return this;
  }

  /**
   * Get resourceAttributeList
   * @return resourceAttributeList
   */
  @javax.annotation.Nullable
  public List getResourceAttributeList() {
    return resourceAttributeList;
  }

  public void setResourceAttributeList(@javax.annotation.Nullable List resourceAttributeList) {
    this.resourceAttributeList = resourceAttributeList;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DescribeMigrationTaskResultMigrationTask describeMigrationTaskResultMigrationTask = (DescribeMigrationTaskResultMigrationTask) o;
    return Objects.equals(this.progressUpdateStream, describeMigrationTaskResultMigrationTask.progressUpdateStream) &&
        Objects.equals(this.migrationTaskName, describeMigrationTaskResultMigrationTask.migrationTaskName) &&
        Objects.equals(this.task, describeMigrationTaskResultMigrationTask.task) &&
        Objects.equals(this.updateDateTime, describeMigrationTaskResultMigrationTask.updateDateTime) &&
        Objects.equals(this.resourceAttributeList, describeMigrationTaskResultMigrationTask.resourceAttributeList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(progressUpdateStream, migrationTaskName, task, updateDateTime, resourceAttributeList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DescribeMigrationTaskResultMigrationTask {\n");
    sb.append("    progressUpdateStream: ").append(toIndentedString(progressUpdateStream)).append("\n");
    sb.append("    migrationTaskName: ").append(toIndentedString(migrationTaskName)).append("\n");
    sb.append("    task: ").append(toIndentedString(task)).append("\n");
    sb.append("    updateDateTime: ").append(toIndentedString(updateDateTime)).append("\n");
    sb.append("    resourceAttributeList: ").append(toIndentedString(resourceAttributeList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("ProgressUpdateStream");
    openapiFields.add("MigrationTaskName");
    openapiFields.add("Task");
    openapiFields.add("UpdateDateTime");
    openapiFields.add("ResourceAttributeList");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DescribeMigrationTaskResultMigrationTask
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DescribeMigrationTaskResultMigrationTask.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DescribeMigrationTaskResultMigrationTask is not found in the empty JSON string", DescribeMigrationTaskResultMigrationTask.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DescribeMigrationTaskResultMigrationTask.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DescribeMigrationTaskResultMigrationTask` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `ProgressUpdateStream`
      if (jsonObj.get("ProgressUpdateStream") != null && !jsonObj.get("ProgressUpdateStream").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("ProgressUpdateStream"));
      }
      // validate the optional field `MigrationTaskName`
      if (jsonObj.get("MigrationTaskName") != null && !jsonObj.get("MigrationTaskName").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("MigrationTaskName"));
      }
      // validate the optional field `Task`
      if (jsonObj.get("Task") != null && !jsonObj.get("Task").isJsonNull()) {
        MigrationTaskTask.validateJsonElement(jsonObj.get("Task"));
      }
      // validate the optional field `UpdateDateTime`
      if (jsonObj.get("UpdateDateTime") != null && !jsonObj.get("UpdateDateTime").isJsonNull()) {
        OffsetDateTime.validateJsonElement(jsonObj.get("UpdateDateTime"));
      }
      // validate the optional field `ResourceAttributeList`
      if (jsonObj.get("ResourceAttributeList") != null && !jsonObj.get("ResourceAttributeList").isJsonNull()) {
        List.validateJsonElement(jsonObj.get("ResourceAttributeList"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DescribeMigrationTaskResultMigrationTask.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DescribeMigrationTaskResultMigrationTask' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DescribeMigrationTaskResultMigrationTask> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DescribeMigrationTaskResultMigrationTask.class));

       return (TypeAdapter<T>) new TypeAdapter<DescribeMigrationTaskResultMigrationTask>() {
           @Override
           public void write(JsonWriter out, DescribeMigrationTaskResultMigrationTask value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DescribeMigrationTaskResultMigrationTask read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DescribeMigrationTaskResultMigrationTask given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DescribeMigrationTaskResultMigrationTask
   * @throws IOException if the JSON string is invalid with respect to DescribeMigrationTaskResultMigrationTask
   */
  public static DescribeMigrationTaskResultMigrationTask fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DescribeMigrationTaskResultMigrationTask.class);
  }

  /**
   * Convert an instance of DescribeMigrationTaskResultMigrationTask to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

