/*
 * AWS Migration Hub
 * <p>The AWS Migration Hub API methods help to obtain server and application migration status and integrate your resource-specific migration tool by providing a programmatic interface to Migration Hub.</p> <p>Remember that you must set your AWS Migration Hub home region before you call any of these APIs, or a <code>HomeRegionNotSetException</code> error will be returned. Also, you must make the API calls while in your home region.</p>
 *
 * The version of the OpenAPI document: 2017-05-31
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ListDiscoveredResourcesRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:02:31.467047+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class ListDiscoveredResourcesRequest {
  public static final String SERIALIZED_NAME_PROGRESS_UPDATE_STREAM = "ProgressUpdateStream";
  @SerializedName(SERIALIZED_NAME_PROGRESS_UPDATE_STREAM)
  @javax.annotation.Nonnull
  private String progressUpdateStream;

  public static final String SERIALIZED_NAME_MIGRATION_TASK_NAME = "MigrationTaskName";
  @SerializedName(SERIALIZED_NAME_MIGRATION_TASK_NAME)
  @javax.annotation.Nonnull
  private String migrationTaskName;

  public static final String SERIALIZED_NAME_NEXT_TOKEN = "NextToken";
  @SerializedName(SERIALIZED_NAME_NEXT_TOKEN)
  @javax.annotation.Nullable
  private String nextToken;

  public static final String SERIALIZED_NAME_MAX_RESULTS = "MaxResults";
  @SerializedName(SERIALIZED_NAME_MAX_RESULTS)
  @javax.annotation.Nullable
  private Integer maxResults;

  public ListDiscoveredResourcesRequest() {
  }

  public ListDiscoveredResourcesRequest progressUpdateStream(@javax.annotation.Nonnull String progressUpdateStream) {
    this.progressUpdateStream = progressUpdateStream;
    return this;
  }

  /**
   * Get progressUpdateStream
   * @return progressUpdateStream
   */
  @javax.annotation.Nonnull
  public String getProgressUpdateStream() {
    return progressUpdateStream;
  }

  public void setProgressUpdateStream(@javax.annotation.Nonnull String progressUpdateStream) {
    this.progressUpdateStream = progressUpdateStream;
  }


  public ListDiscoveredResourcesRequest migrationTaskName(@javax.annotation.Nonnull String migrationTaskName) {
    this.migrationTaskName = migrationTaskName;
    return this;
  }

  /**
   * Get migrationTaskName
   * @return migrationTaskName
   */
  @javax.annotation.Nonnull
  public String getMigrationTaskName() {
    return migrationTaskName;
  }

  public void setMigrationTaskName(@javax.annotation.Nonnull String migrationTaskName) {
    this.migrationTaskName = migrationTaskName;
  }


  public ListDiscoveredResourcesRequest nextToken(@javax.annotation.Nullable String nextToken) {
    this.nextToken = nextToken;
    return this;
  }

  /**
   * Get nextToken
   * @return nextToken
   */
  @javax.annotation.Nullable
  public String getNextToken() {
    return nextToken;
  }

  public void setNextToken(@javax.annotation.Nullable String nextToken) {
    this.nextToken = nextToken;
  }


  public ListDiscoveredResourcesRequest maxResults(@javax.annotation.Nullable Integer maxResults) {
    this.maxResults = maxResults;
    return this;
  }

  /**
   * Get maxResults
   * @return maxResults
   */
  @javax.annotation.Nullable
  public Integer getMaxResults() {
    return maxResults;
  }

  public void setMaxResults(@javax.annotation.Nullable Integer maxResults) {
    this.maxResults = maxResults;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListDiscoveredResourcesRequest listDiscoveredResourcesRequest = (ListDiscoveredResourcesRequest) o;
    return Objects.equals(this.progressUpdateStream, listDiscoveredResourcesRequest.progressUpdateStream) &&
        Objects.equals(this.migrationTaskName, listDiscoveredResourcesRequest.migrationTaskName) &&
        Objects.equals(this.nextToken, listDiscoveredResourcesRequest.nextToken) &&
        Objects.equals(this.maxResults, listDiscoveredResourcesRequest.maxResults);
  }

  @Override
  public int hashCode() {
    return Objects.hash(progressUpdateStream, migrationTaskName, nextToken, maxResults);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListDiscoveredResourcesRequest {\n");
    sb.append("    progressUpdateStream: ").append(toIndentedString(progressUpdateStream)).append("\n");
    sb.append("    migrationTaskName: ").append(toIndentedString(migrationTaskName)).append("\n");
    sb.append("    nextToken: ").append(toIndentedString(nextToken)).append("\n");
    sb.append("    maxResults: ").append(toIndentedString(maxResults)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("ProgressUpdateStream");
    openapiFields.add("MigrationTaskName");
    openapiFields.add("NextToken");
    openapiFields.add("MaxResults");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("ProgressUpdateStream");
    openapiRequiredFields.add("MigrationTaskName");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ListDiscoveredResourcesRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ListDiscoveredResourcesRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ListDiscoveredResourcesRequest is not found in the empty JSON string", ListDiscoveredResourcesRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ListDiscoveredResourcesRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ListDiscoveredResourcesRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ListDiscoveredResourcesRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `ProgressUpdateStream`
      String.validateJsonElement(jsonObj.get("ProgressUpdateStream"));
      // validate the required field `MigrationTaskName`
      String.validateJsonElement(jsonObj.get("MigrationTaskName"));
      // validate the optional field `NextToken`
      if (jsonObj.get("NextToken") != null && !jsonObj.get("NextToken").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("NextToken"));
      }
      // validate the optional field `MaxResults`
      if (jsonObj.get("MaxResults") != null && !jsonObj.get("MaxResults").isJsonNull()) {
        Integer.validateJsonElement(jsonObj.get("MaxResults"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ListDiscoveredResourcesRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ListDiscoveredResourcesRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ListDiscoveredResourcesRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ListDiscoveredResourcesRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<ListDiscoveredResourcesRequest>() {
           @Override
           public void write(JsonWriter out, ListDiscoveredResourcesRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ListDiscoveredResourcesRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ListDiscoveredResourcesRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ListDiscoveredResourcesRequest
   * @throws IOException if the JSON string is invalid with respect to ListDiscoveredResourcesRequest
   */
  public static ListDiscoveredResourcesRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ListDiscoveredResourcesRequest.class);
  }

  /**
   * Convert an instance of ListDiscoveredResourcesRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

