/*
 * AWS Migration Hub
 * <p>The AWS Migration Hub API methods help to obtain server and application migration status and integrate your resource-specific migration tool by providing a programmatic interface to Migration Hub.</p> <p>Remember that you must set your AWS Migration Hub home region before you call any of these APIs, or a <code>HomeRegionNotSetException</code> error will be returned. Also, you must make the API calls while in your home region.</p>
 *
 * The version of the OpenAPI document: 2017-05-31
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ListApplicationStatesResult
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:02:31.467047+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class ListApplicationStatesResult {
  public static final String SERIALIZED_NAME_APPLICATION_STATE_LIST = "ApplicationStateList";
  @SerializedName(SERIALIZED_NAME_APPLICATION_STATE_LIST)
  @javax.annotation.Nullable
  private List applicationStateList;

  public static final String SERIALIZED_NAME_NEXT_TOKEN = "NextToken";
  @SerializedName(SERIALIZED_NAME_NEXT_TOKEN)
  @javax.annotation.Nullable
  private String nextToken;

  public ListApplicationStatesResult() {
  }

  public ListApplicationStatesResult applicationStateList(@javax.annotation.Nullable List applicationStateList) {
    this.applicationStateList = applicationStateList;
    return this;
  }

  /**
   * Get applicationStateList
   * @return applicationStateList
   */
  @javax.annotation.Nullable
  public List getApplicationStateList() {
    return applicationStateList;
  }

  public void setApplicationStateList(@javax.annotation.Nullable List applicationStateList) {
    this.applicationStateList = applicationStateList;
  }


  public ListApplicationStatesResult nextToken(@javax.annotation.Nullable String nextToken) {
    this.nextToken = nextToken;
    return this;
  }

  /**
   * Get nextToken
   * @return nextToken
   */
  @javax.annotation.Nullable
  public String getNextToken() {
    return nextToken;
  }

  public void setNextToken(@javax.annotation.Nullable String nextToken) {
    this.nextToken = nextToken;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListApplicationStatesResult listApplicationStatesResult = (ListApplicationStatesResult) o;
    return Objects.equals(this.applicationStateList, listApplicationStatesResult.applicationStateList) &&
        Objects.equals(this.nextToken, listApplicationStatesResult.nextToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(applicationStateList, nextToken);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListApplicationStatesResult {\n");
    sb.append("    applicationStateList: ").append(toIndentedString(applicationStateList)).append("\n");
    sb.append("    nextToken: ").append(toIndentedString(nextToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("ApplicationStateList");
    openapiFields.add("NextToken");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ListApplicationStatesResult
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ListApplicationStatesResult.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ListApplicationStatesResult is not found in the empty JSON string", ListApplicationStatesResult.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ListApplicationStatesResult.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ListApplicationStatesResult` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `ApplicationStateList`
      if (jsonObj.get("ApplicationStateList") != null && !jsonObj.get("ApplicationStateList").isJsonNull()) {
        List.validateJsonElement(jsonObj.get("ApplicationStateList"));
      }
      // validate the optional field `NextToken`
      if (jsonObj.get("NextToken") != null && !jsonObj.get("NextToken").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("NextToken"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ListApplicationStatesResult.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ListApplicationStatesResult' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ListApplicationStatesResult> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ListApplicationStatesResult.class));

       return (TypeAdapter<T>) new TypeAdapter<ListApplicationStatesResult>() {
           @Override
           public void write(JsonWriter out, ListApplicationStatesResult value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ListApplicationStatesResult read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ListApplicationStatesResult given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ListApplicationStatesResult
   * @throws IOException if the JSON string is invalid with respect to ListApplicationStatesResult
   */
  public static ListApplicationStatesResult fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ListApplicationStatesResult.class);
  }

  /**
   * Convert an instance of ListApplicationStatesResult to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

