/*
 * AWS Migration Hub
 * <p>The AWS Migration Hub API methods help to obtain server and application migration status and integrate your resource-specific migration tool by providing a programmatic interface to Migration Hub.</p> <p>Remember that you must set your AWS Migration Hub home region before you call any of these APIs, or a <code>HomeRegionNotSetException</code> error will be returned. Also, you must make the API calls while in your home region.</p>
 *
 * The version of the OpenAPI document: 2017-05-31
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ListDiscoveredResourcesResult
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:02:31.467047+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class ListDiscoveredResourcesResult {
  public static final String SERIALIZED_NAME_NEXT_TOKEN = "NextToken";
  @SerializedName(SERIALIZED_NAME_NEXT_TOKEN)
  @javax.annotation.Nullable
  private String nextToken;

  public static final String SERIALIZED_NAME_DISCOVERED_RESOURCE_LIST = "DiscoveredResourceList";
  @SerializedName(SERIALIZED_NAME_DISCOVERED_RESOURCE_LIST)
  @javax.annotation.Nullable
  private List discoveredResourceList;

  public ListDiscoveredResourcesResult() {
  }

  public ListDiscoveredResourcesResult nextToken(@javax.annotation.Nullable String nextToken) {
    this.nextToken = nextToken;
    return this;
  }

  /**
   * Get nextToken
   * @return nextToken
   */
  @javax.annotation.Nullable
  public String getNextToken() {
    return nextToken;
  }

  public void setNextToken(@javax.annotation.Nullable String nextToken) {
    this.nextToken = nextToken;
  }


  public ListDiscoveredResourcesResult discoveredResourceList(@javax.annotation.Nullable List discoveredResourceList) {
    this.discoveredResourceList = discoveredResourceList;
    return this;
  }

  /**
   * Get discoveredResourceList
   * @return discoveredResourceList
   */
  @javax.annotation.Nullable
  public List getDiscoveredResourceList() {
    return discoveredResourceList;
  }

  public void setDiscoveredResourceList(@javax.annotation.Nullable List discoveredResourceList) {
    this.discoveredResourceList = discoveredResourceList;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListDiscoveredResourcesResult listDiscoveredResourcesResult = (ListDiscoveredResourcesResult) o;
    return Objects.equals(this.nextToken, listDiscoveredResourcesResult.nextToken) &&
        Objects.equals(this.discoveredResourceList, listDiscoveredResourcesResult.discoveredResourceList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nextToken, discoveredResourceList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListDiscoveredResourcesResult {\n");
    sb.append("    nextToken: ").append(toIndentedString(nextToken)).append("\n");
    sb.append("    discoveredResourceList: ").append(toIndentedString(discoveredResourceList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("NextToken");
    openapiFields.add("DiscoveredResourceList");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ListDiscoveredResourcesResult
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ListDiscoveredResourcesResult.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ListDiscoveredResourcesResult is not found in the empty JSON string", ListDiscoveredResourcesResult.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ListDiscoveredResourcesResult.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ListDiscoveredResourcesResult` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `NextToken`
      if (jsonObj.get("NextToken") != null && !jsonObj.get("NextToken").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("NextToken"));
      }
      // validate the optional field `DiscoveredResourceList`
      if (jsonObj.get("DiscoveredResourceList") != null && !jsonObj.get("DiscoveredResourceList").isJsonNull()) {
        List.validateJsonElement(jsonObj.get("DiscoveredResourceList"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ListDiscoveredResourcesResult.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ListDiscoveredResourcesResult' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ListDiscoveredResourcesResult> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ListDiscoveredResourcesResult.class));

       return (TypeAdapter<T>) new TypeAdapter<ListDiscoveredResourcesResult>() {
           @Override
           public void write(JsonWriter out, ListDiscoveredResourcesResult value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ListDiscoveredResourcesResult read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ListDiscoveredResourcesResult given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ListDiscoveredResourcesResult
   * @throws IOException if the JSON string is invalid with respect to ListDiscoveredResourcesResult
   */
  public static ListDiscoveredResourcesResult fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ListDiscoveredResourcesResult.class);
  }

  /**
   * Convert an instance of ListDiscoveredResourcesResult to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

