/*
 * AWS Migration Hub
 * <p>The AWS Migration Hub API methods help to obtain server and application migration status and integrate your resource-specific migration tool by providing a programmatic interface to Migration Hub.</p> <p>Remember that you must set your AWS Migration Hub home region before you call any of these APIs, or a <code>HomeRegionNotSetException</code> error will be returned. Also, you must make the API calls while in your home region.</p>
 *
 * The version of the OpenAPI document: 2017-05-31
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.client.model.Status;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * MigrationTaskSummary includes &lt;code&gt;MigrationTaskName&lt;/code&gt;, &lt;code&gt;ProgressPercent&lt;/code&gt;, &lt;code&gt;ProgressUpdateStream&lt;/code&gt;, &lt;code&gt;Status&lt;/code&gt;, and &lt;code&gt;UpdateDateTime&lt;/code&gt; for each task.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:02:31.467047+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class MigrationTaskSummary {
  public static final String SERIALIZED_NAME_PROGRESS_UPDATE_STREAM = "ProgressUpdateStream";
  @SerializedName(SERIALIZED_NAME_PROGRESS_UPDATE_STREAM)
  @javax.annotation.Nullable
  private String progressUpdateStream;

  public static final String SERIALIZED_NAME_MIGRATION_TASK_NAME = "MigrationTaskName";
  @SerializedName(SERIALIZED_NAME_MIGRATION_TASK_NAME)
  @javax.annotation.Nullable
  private String migrationTaskName;

  public static final String SERIALIZED_NAME_STATUS = "Status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private Status status;

  public static final String SERIALIZED_NAME_PROGRESS_PERCENT = "ProgressPercent";
  @SerializedName(SERIALIZED_NAME_PROGRESS_PERCENT)
  @javax.annotation.Nullable
  private Integer progressPercent;

  public static final String SERIALIZED_NAME_STATUS_DETAIL = "StatusDetail";
  @SerializedName(SERIALIZED_NAME_STATUS_DETAIL)
  @javax.annotation.Nullable
  private String statusDetail;

  public static final String SERIALIZED_NAME_UPDATE_DATE_TIME = "UpdateDateTime";
  @SerializedName(SERIALIZED_NAME_UPDATE_DATE_TIME)
  @javax.annotation.Nullable
  private OffsetDateTime updateDateTime;

  public MigrationTaskSummary() {
  }

  public MigrationTaskSummary progressUpdateStream(@javax.annotation.Nullable String progressUpdateStream) {
    this.progressUpdateStream = progressUpdateStream;
    return this;
  }

  /**
   * Get progressUpdateStream
   * @return progressUpdateStream
   */
  @javax.annotation.Nullable
  public String getProgressUpdateStream() {
    return progressUpdateStream;
  }

  public void setProgressUpdateStream(@javax.annotation.Nullable String progressUpdateStream) {
    this.progressUpdateStream = progressUpdateStream;
  }


  public MigrationTaskSummary migrationTaskName(@javax.annotation.Nullable String migrationTaskName) {
    this.migrationTaskName = migrationTaskName;
    return this;
  }

  /**
   * Get migrationTaskName
   * @return migrationTaskName
   */
  @javax.annotation.Nullable
  public String getMigrationTaskName() {
    return migrationTaskName;
  }

  public void setMigrationTaskName(@javax.annotation.Nullable String migrationTaskName) {
    this.migrationTaskName = migrationTaskName;
  }


  public MigrationTaskSummary status(@javax.annotation.Nullable Status status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  public Status getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable Status status) {
    this.status = status;
  }


  public MigrationTaskSummary progressPercent(@javax.annotation.Nullable Integer progressPercent) {
    this.progressPercent = progressPercent;
    return this;
  }

  /**
   * Get progressPercent
   * @return progressPercent
   */
  @javax.annotation.Nullable
  public Integer getProgressPercent() {
    return progressPercent;
  }

  public void setProgressPercent(@javax.annotation.Nullable Integer progressPercent) {
    this.progressPercent = progressPercent;
  }


  public MigrationTaskSummary statusDetail(@javax.annotation.Nullable String statusDetail) {
    this.statusDetail = statusDetail;
    return this;
  }

  /**
   * Get statusDetail
   * @return statusDetail
   */
  @javax.annotation.Nullable
  public String getStatusDetail() {
    return statusDetail;
  }

  public void setStatusDetail(@javax.annotation.Nullable String statusDetail) {
    this.statusDetail = statusDetail;
  }


  public MigrationTaskSummary updateDateTime(@javax.annotation.Nullable OffsetDateTime updateDateTime) {
    this.updateDateTime = updateDateTime;
    return this;
  }

  /**
   * Get updateDateTime
   * @return updateDateTime
   */
  @javax.annotation.Nullable
  public OffsetDateTime getUpdateDateTime() {
    return updateDateTime;
  }

  public void setUpdateDateTime(@javax.annotation.Nullable OffsetDateTime updateDateTime) {
    this.updateDateTime = updateDateTime;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MigrationTaskSummary migrationTaskSummary = (MigrationTaskSummary) o;
    return Objects.equals(this.progressUpdateStream, migrationTaskSummary.progressUpdateStream) &&
        Objects.equals(this.migrationTaskName, migrationTaskSummary.migrationTaskName) &&
        Objects.equals(this.status, migrationTaskSummary.status) &&
        Objects.equals(this.progressPercent, migrationTaskSummary.progressPercent) &&
        Objects.equals(this.statusDetail, migrationTaskSummary.statusDetail) &&
        Objects.equals(this.updateDateTime, migrationTaskSummary.updateDateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(progressUpdateStream, migrationTaskName, status, progressPercent, statusDetail, updateDateTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MigrationTaskSummary {\n");
    sb.append("    progressUpdateStream: ").append(toIndentedString(progressUpdateStream)).append("\n");
    sb.append("    migrationTaskName: ").append(toIndentedString(migrationTaskName)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    progressPercent: ").append(toIndentedString(progressPercent)).append("\n");
    sb.append("    statusDetail: ").append(toIndentedString(statusDetail)).append("\n");
    sb.append("    updateDateTime: ").append(toIndentedString(updateDateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("ProgressUpdateStream");
    openapiFields.add("MigrationTaskName");
    openapiFields.add("Status");
    openapiFields.add("ProgressPercent");
    openapiFields.add("StatusDetail");
    openapiFields.add("UpdateDateTime");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MigrationTaskSummary
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MigrationTaskSummary.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in MigrationTaskSummary is not found in the empty JSON string", MigrationTaskSummary.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!MigrationTaskSummary.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `MigrationTaskSummary` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `ProgressUpdateStream`
      if (jsonObj.get("ProgressUpdateStream") != null && !jsonObj.get("ProgressUpdateStream").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("ProgressUpdateStream"));
      }
      // validate the optional field `MigrationTaskName`
      if (jsonObj.get("MigrationTaskName") != null && !jsonObj.get("MigrationTaskName").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("MigrationTaskName"));
      }
      // validate the optional field `Status`
      if (jsonObj.get("Status") != null && !jsonObj.get("Status").isJsonNull()) {
        Status.validateJsonElement(jsonObj.get("Status"));
      }
      // validate the optional field `ProgressPercent`
      if (jsonObj.get("ProgressPercent") != null && !jsonObj.get("ProgressPercent").isJsonNull()) {
        Integer.validateJsonElement(jsonObj.get("ProgressPercent"));
      }
      // validate the optional field `StatusDetail`
      if (jsonObj.get("StatusDetail") != null && !jsonObj.get("StatusDetail").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("StatusDetail"));
      }
      // validate the optional field `UpdateDateTime`
      if (jsonObj.get("UpdateDateTime") != null && !jsonObj.get("UpdateDateTime").isJsonNull()) {
        OffsetDateTime.validateJsonElement(jsonObj.get("UpdateDateTime"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MigrationTaskSummary.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MigrationTaskSummary' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MigrationTaskSummary> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MigrationTaskSummary.class));

       return (TypeAdapter<T>) new TypeAdapter<MigrationTaskSummary>() {
           @Override
           public void write(JsonWriter out, MigrationTaskSummary value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MigrationTaskSummary read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MigrationTaskSummary given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MigrationTaskSummary
   * @throws IOException if the JSON string is invalid with respect to MigrationTaskSummary
   */
  public static MigrationTaskSummary fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MigrationTaskSummary.class);
  }

  /**
   * Convert an instance of MigrationTaskSummary to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

