/*
 * AWS Migration Hub
 * <p>The AWS Migration Hub API methods help to obtain server and application migration status and integrate your resource-specific migration tool by providing a programmatic interface to Migration Hub.</p> <p>Remember that you must set your AWS Migration Hub home region before you call any of these APIs, or a <code>HomeRegionNotSetException</code> error will be returned. Also, you must make the API calls while in your home region.</p>
 *
 * The version of the OpenAPI document: 2017-05-31
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.client.model.NotifyMigrationTaskStateRequestTask;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * NotifyMigrationTaskStateRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:02:31.467047+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class NotifyMigrationTaskStateRequest {
  public static final String SERIALIZED_NAME_PROGRESS_UPDATE_STREAM = "ProgressUpdateStream";
  @SerializedName(SERIALIZED_NAME_PROGRESS_UPDATE_STREAM)
  @javax.annotation.Nonnull
  private String progressUpdateStream;

  public static final String SERIALIZED_NAME_MIGRATION_TASK_NAME = "MigrationTaskName";
  @SerializedName(SERIALIZED_NAME_MIGRATION_TASK_NAME)
  @javax.annotation.Nonnull
  private String migrationTaskName;

  public static final String SERIALIZED_NAME_TASK = "Task";
  @SerializedName(SERIALIZED_NAME_TASK)
  @javax.annotation.Nonnull
  private NotifyMigrationTaskStateRequestTask task;

  public static final String SERIALIZED_NAME_UPDATE_DATE_TIME = "UpdateDateTime";
  @SerializedName(SERIALIZED_NAME_UPDATE_DATE_TIME)
  @javax.annotation.Nonnull
  private OffsetDateTime updateDateTime;

  public static final String SERIALIZED_NAME_NEXT_UPDATE_SECONDS = "NextUpdateSeconds";
  @SerializedName(SERIALIZED_NAME_NEXT_UPDATE_SECONDS)
  @javax.annotation.Nonnull
  private Integer nextUpdateSeconds;

  public static final String SERIALIZED_NAME_DRY_RUN = "DryRun";
  @SerializedName(SERIALIZED_NAME_DRY_RUN)
  @javax.annotation.Nullable
  private Boolean dryRun;

  public NotifyMigrationTaskStateRequest() {
  }

  public NotifyMigrationTaskStateRequest progressUpdateStream(@javax.annotation.Nonnull String progressUpdateStream) {
    this.progressUpdateStream = progressUpdateStream;
    return this;
  }

  /**
   * Get progressUpdateStream
   * @return progressUpdateStream
   */
  @javax.annotation.Nonnull
  public String getProgressUpdateStream() {
    return progressUpdateStream;
  }

  public void setProgressUpdateStream(@javax.annotation.Nonnull String progressUpdateStream) {
    this.progressUpdateStream = progressUpdateStream;
  }


  public NotifyMigrationTaskStateRequest migrationTaskName(@javax.annotation.Nonnull String migrationTaskName) {
    this.migrationTaskName = migrationTaskName;
    return this;
  }

  /**
   * Get migrationTaskName
   * @return migrationTaskName
   */
  @javax.annotation.Nonnull
  public String getMigrationTaskName() {
    return migrationTaskName;
  }

  public void setMigrationTaskName(@javax.annotation.Nonnull String migrationTaskName) {
    this.migrationTaskName = migrationTaskName;
  }


  public NotifyMigrationTaskStateRequest task(@javax.annotation.Nonnull NotifyMigrationTaskStateRequestTask task) {
    this.task = task;
    return this;
  }

  /**
   * Get task
   * @return task
   */
  @javax.annotation.Nonnull
  public NotifyMigrationTaskStateRequestTask getTask() {
    return task;
  }

  public void setTask(@javax.annotation.Nonnull NotifyMigrationTaskStateRequestTask task) {
    this.task = task;
  }


  public NotifyMigrationTaskStateRequest updateDateTime(@javax.annotation.Nonnull OffsetDateTime updateDateTime) {
    this.updateDateTime = updateDateTime;
    return this;
  }

  /**
   * Get updateDateTime
   * @return updateDateTime
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getUpdateDateTime() {
    return updateDateTime;
  }

  public void setUpdateDateTime(@javax.annotation.Nonnull OffsetDateTime updateDateTime) {
    this.updateDateTime = updateDateTime;
  }


  public NotifyMigrationTaskStateRequest nextUpdateSeconds(@javax.annotation.Nonnull Integer nextUpdateSeconds) {
    this.nextUpdateSeconds = nextUpdateSeconds;
    return this;
  }

  /**
   * Get nextUpdateSeconds
   * @return nextUpdateSeconds
   */
  @javax.annotation.Nonnull
  public Integer getNextUpdateSeconds() {
    return nextUpdateSeconds;
  }

  public void setNextUpdateSeconds(@javax.annotation.Nonnull Integer nextUpdateSeconds) {
    this.nextUpdateSeconds = nextUpdateSeconds;
  }


  public NotifyMigrationTaskStateRequest dryRun(@javax.annotation.Nullable Boolean dryRun) {
    this.dryRun = dryRun;
    return this;
  }

  /**
   * Get dryRun
   * @return dryRun
   */
  @javax.annotation.Nullable
  public Boolean getDryRun() {
    return dryRun;
  }

  public void setDryRun(@javax.annotation.Nullable Boolean dryRun) {
    this.dryRun = dryRun;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NotifyMigrationTaskStateRequest notifyMigrationTaskStateRequest = (NotifyMigrationTaskStateRequest) o;
    return Objects.equals(this.progressUpdateStream, notifyMigrationTaskStateRequest.progressUpdateStream) &&
        Objects.equals(this.migrationTaskName, notifyMigrationTaskStateRequest.migrationTaskName) &&
        Objects.equals(this.task, notifyMigrationTaskStateRequest.task) &&
        Objects.equals(this.updateDateTime, notifyMigrationTaskStateRequest.updateDateTime) &&
        Objects.equals(this.nextUpdateSeconds, notifyMigrationTaskStateRequest.nextUpdateSeconds) &&
        Objects.equals(this.dryRun, notifyMigrationTaskStateRequest.dryRun);
  }

  @Override
  public int hashCode() {
    return Objects.hash(progressUpdateStream, migrationTaskName, task, updateDateTime, nextUpdateSeconds, dryRun);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NotifyMigrationTaskStateRequest {\n");
    sb.append("    progressUpdateStream: ").append(toIndentedString(progressUpdateStream)).append("\n");
    sb.append("    migrationTaskName: ").append(toIndentedString(migrationTaskName)).append("\n");
    sb.append("    task: ").append(toIndentedString(task)).append("\n");
    sb.append("    updateDateTime: ").append(toIndentedString(updateDateTime)).append("\n");
    sb.append("    nextUpdateSeconds: ").append(toIndentedString(nextUpdateSeconds)).append("\n");
    sb.append("    dryRun: ").append(toIndentedString(dryRun)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("ProgressUpdateStream");
    openapiFields.add("MigrationTaskName");
    openapiFields.add("Task");
    openapiFields.add("UpdateDateTime");
    openapiFields.add("NextUpdateSeconds");
    openapiFields.add("DryRun");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("ProgressUpdateStream");
    openapiRequiredFields.add("MigrationTaskName");
    openapiRequiredFields.add("Task");
    openapiRequiredFields.add("UpdateDateTime");
    openapiRequiredFields.add("NextUpdateSeconds");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to NotifyMigrationTaskStateRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!NotifyMigrationTaskStateRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in NotifyMigrationTaskStateRequest is not found in the empty JSON string", NotifyMigrationTaskStateRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!NotifyMigrationTaskStateRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `NotifyMigrationTaskStateRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : NotifyMigrationTaskStateRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `ProgressUpdateStream`
      String.validateJsonElement(jsonObj.get("ProgressUpdateStream"));
      // validate the required field `MigrationTaskName`
      String.validateJsonElement(jsonObj.get("MigrationTaskName"));
      // validate the required field `Task`
      NotifyMigrationTaskStateRequestTask.validateJsonElement(jsonObj.get("Task"));
      // validate the required field `UpdateDateTime`
      OffsetDateTime.validateJsonElement(jsonObj.get("UpdateDateTime"));
      // validate the required field `NextUpdateSeconds`
      Integer.validateJsonElement(jsonObj.get("NextUpdateSeconds"));
      // validate the optional field `DryRun`
      if (jsonObj.get("DryRun") != null && !jsonObj.get("DryRun").isJsonNull()) {
        Boolean.validateJsonElement(jsonObj.get("DryRun"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!NotifyMigrationTaskStateRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'NotifyMigrationTaskStateRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<NotifyMigrationTaskStateRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(NotifyMigrationTaskStateRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<NotifyMigrationTaskStateRequest>() {
           @Override
           public void write(JsonWriter out, NotifyMigrationTaskStateRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public NotifyMigrationTaskStateRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of NotifyMigrationTaskStateRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of NotifyMigrationTaskStateRequest
   * @throws IOException if the JSON string is invalid with respect to NotifyMigrationTaskStateRequest
   */
  public static NotifyMigrationTaskStateRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, NotifyMigrationTaskStateRequest.class);
  }

  /**
   * Convert an instance of NotifyMigrationTaskStateRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

