/*
 * AWS Migration Hub
 * <p>The AWS Migration Hub API methods help to obtain server and application migration status and integrate your resource-specific migration tool by providing a programmatic interface to Migration Hub.</p> <p>Remember that you must set your AWS Migration Hub home region before you call any of these APIs, or a <code>HomeRegionNotSetException</code> error will be returned. Also, you must make the API calls while in your home region.</p>
 *
 * The version of the OpenAPI document: 2017-05-31
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.Status;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * NotifyMigrationTaskStateRequestTask
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:02:31.467047+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class NotifyMigrationTaskStateRequestTask {
  public static final String SERIALIZED_NAME_STATUS = "Status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nonnull
  private Status status;

  public static final String SERIALIZED_NAME_STATUS_DETAIL = "StatusDetail";
  @SerializedName(SERIALIZED_NAME_STATUS_DETAIL)
  @javax.annotation.Nullable
  private String statusDetail;

  public static final String SERIALIZED_NAME_PROGRESS_PERCENT = "ProgressPercent";
  @SerializedName(SERIALIZED_NAME_PROGRESS_PERCENT)
  @javax.annotation.Nullable
  private Integer progressPercent;

  public NotifyMigrationTaskStateRequestTask() {
  }

  public NotifyMigrationTaskStateRequestTask status(@javax.annotation.Nonnull Status status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  public Status getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nonnull Status status) {
    this.status = status;
  }


  public NotifyMigrationTaskStateRequestTask statusDetail(@javax.annotation.Nullable String statusDetail) {
    this.statusDetail = statusDetail;
    return this;
  }

  /**
   * Get statusDetail
   * @return statusDetail
   */
  @javax.annotation.Nullable
  public String getStatusDetail() {
    return statusDetail;
  }

  public void setStatusDetail(@javax.annotation.Nullable String statusDetail) {
    this.statusDetail = statusDetail;
  }


  public NotifyMigrationTaskStateRequestTask progressPercent(@javax.annotation.Nullable Integer progressPercent) {
    this.progressPercent = progressPercent;
    return this;
  }

  /**
   * Get progressPercent
   * @return progressPercent
   */
  @javax.annotation.Nullable
  public Integer getProgressPercent() {
    return progressPercent;
  }

  public void setProgressPercent(@javax.annotation.Nullable Integer progressPercent) {
    this.progressPercent = progressPercent;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NotifyMigrationTaskStateRequestTask notifyMigrationTaskStateRequestTask = (NotifyMigrationTaskStateRequestTask) o;
    return Objects.equals(this.status, notifyMigrationTaskStateRequestTask.status) &&
        Objects.equals(this.statusDetail, notifyMigrationTaskStateRequestTask.statusDetail) &&
        Objects.equals(this.progressPercent, notifyMigrationTaskStateRequestTask.progressPercent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, statusDetail, progressPercent);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NotifyMigrationTaskStateRequestTask {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    statusDetail: ").append(toIndentedString(statusDetail)).append("\n");
    sb.append("    progressPercent: ").append(toIndentedString(progressPercent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("Status");
    openapiFields.add("StatusDetail");
    openapiFields.add("ProgressPercent");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("Status");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to NotifyMigrationTaskStateRequestTask
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!NotifyMigrationTaskStateRequestTask.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in NotifyMigrationTaskStateRequestTask is not found in the empty JSON string", NotifyMigrationTaskStateRequestTask.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!NotifyMigrationTaskStateRequestTask.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `NotifyMigrationTaskStateRequestTask` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : NotifyMigrationTaskStateRequestTask.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `Status`
      Status.validateJsonElement(jsonObj.get("Status"));
      // validate the optional field `StatusDetail`
      if (jsonObj.get("StatusDetail") != null && !jsonObj.get("StatusDetail").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("StatusDetail"));
      }
      // validate the optional field `ProgressPercent`
      if (jsonObj.get("ProgressPercent") != null && !jsonObj.get("ProgressPercent").isJsonNull()) {
        Integer.validateJsonElement(jsonObj.get("ProgressPercent"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!NotifyMigrationTaskStateRequestTask.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'NotifyMigrationTaskStateRequestTask' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<NotifyMigrationTaskStateRequestTask> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(NotifyMigrationTaskStateRequestTask.class));

       return (TypeAdapter<T>) new TypeAdapter<NotifyMigrationTaskStateRequestTask>() {
           @Override
           public void write(JsonWriter out, NotifyMigrationTaskStateRequestTask value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public NotifyMigrationTaskStateRequestTask read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of NotifyMigrationTaskStateRequestTask given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of NotifyMigrationTaskStateRequestTask
   * @throws IOException if the JSON string is invalid with respect to NotifyMigrationTaskStateRequestTask
   */
  public static NotifyMigrationTaskStateRequestTask fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, NotifyMigrationTaskStateRequestTask.class);
  }

  /**
   * Convert an instance of NotifyMigrationTaskStateRequestTask to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

