/*
 * AWS Migration Hub
 * <p>The AWS Migration Hub API methods help to obtain server and application migration status and integrate your resource-specific migration tool by providing a programmatic interface to Migration Hub.</p> <p>Remember that you must set your AWS Migration Hub home region before you call any of these APIs, or a <code>HomeRegionNotSetException</code> error will be returned. Also, you must make the API calls while in your home region.</p>
 *
 * The version of the OpenAPI document: 2017-05-31
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Summary of the AWS resource used for access control that is implicitly linked to your AWS account.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:02:31.467047+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class ProgressUpdateStreamSummary {
  public static final String SERIALIZED_NAME_PROGRESS_UPDATE_STREAM_NAME = "ProgressUpdateStreamName";
  @SerializedName(SERIALIZED_NAME_PROGRESS_UPDATE_STREAM_NAME)
  @javax.annotation.Nullable
  private String progressUpdateStreamName;

  public ProgressUpdateStreamSummary() {
  }

  public ProgressUpdateStreamSummary progressUpdateStreamName(@javax.annotation.Nullable String progressUpdateStreamName) {
    this.progressUpdateStreamName = progressUpdateStreamName;
    return this;
  }

  /**
   * Get progressUpdateStreamName
   * @return progressUpdateStreamName
   */
  @javax.annotation.Nullable
  public String getProgressUpdateStreamName() {
    return progressUpdateStreamName;
  }

  public void setProgressUpdateStreamName(@javax.annotation.Nullable String progressUpdateStreamName) {
    this.progressUpdateStreamName = progressUpdateStreamName;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProgressUpdateStreamSummary progressUpdateStreamSummary = (ProgressUpdateStreamSummary) o;
    return Objects.equals(this.progressUpdateStreamName, progressUpdateStreamSummary.progressUpdateStreamName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(progressUpdateStreamName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProgressUpdateStreamSummary {\n");
    sb.append("    progressUpdateStreamName: ").append(toIndentedString(progressUpdateStreamName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("ProgressUpdateStreamName");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ProgressUpdateStreamSummary
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ProgressUpdateStreamSummary.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ProgressUpdateStreamSummary is not found in the empty JSON string", ProgressUpdateStreamSummary.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ProgressUpdateStreamSummary.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ProgressUpdateStreamSummary` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `ProgressUpdateStreamName`
      if (jsonObj.get("ProgressUpdateStreamName") != null && !jsonObj.get("ProgressUpdateStreamName").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("ProgressUpdateStreamName"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ProgressUpdateStreamSummary.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ProgressUpdateStreamSummary' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ProgressUpdateStreamSummary> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ProgressUpdateStreamSummary.class));

       return (TypeAdapter<T>) new TypeAdapter<ProgressUpdateStreamSummary>() {
           @Override
           public void write(JsonWriter out, ProgressUpdateStreamSummary value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ProgressUpdateStreamSummary read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ProgressUpdateStreamSummary given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ProgressUpdateStreamSummary
   * @throws IOException if the JSON string is invalid with respect to ProgressUpdateStreamSummary
   */
  public static ProgressUpdateStreamSummary fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ProgressUpdateStreamSummary.class);
  }

  /**
   * Convert an instance of ProgressUpdateStreamSummary to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

