/*
 * AWS Migration Hub
 * <p>The AWS Migration Hub API methods help to obtain server and application migration status and integrate your resource-specific migration tool by providing a programmatic interface to Migration Hub.</p> <p>Remember that you must set your AWS Migration Hub home region before you call any of these APIs, or a <code>HomeRegionNotSetException</code> error will be returned. Also, you must make the API calls while in your home region.</p>
 *
 * The version of the OpenAPI document: 2017-05-31
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets ResourceAttributeType
 */
@JsonAdapter(ResourceAttributeType.Adapter.class)
public enum ResourceAttributeType {
  
  IPV4_ADDRESS("IPV4_ADDRESS"),
  
  IPV6_ADDRESS("IPV6_ADDRESS"),
  
  MAC_ADDRESS("MAC_ADDRESS"),
  
  FQDN("FQDN"),
  
  VM_MANAGER_ID("VM_MANAGER_ID"),
  
  VM_MANAGED_OBJECT_REFERENCE("VM_MANAGED_OBJECT_REFERENCE"),
  
  VM_NAME("VM_NAME"),
  
  VM_PATH("VM_PATH"),
  
  BIOS_ID("BIOS_ID"),
  
  MOTHERBOARD_SERIAL_NUMBER("MOTHERBOARD_SERIAL_NUMBER");

  private String value;

  ResourceAttributeType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ResourceAttributeType fromValue(String value) {
    for (ResourceAttributeType b : ResourceAttributeType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<ResourceAttributeType> {
    @Override
    public void write(final JsonWriter jsonWriter, final ResourceAttributeType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ResourceAttributeType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ResourceAttributeType.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    ResourceAttributeType.fromValue(value);
  }
}

