/*
 * AWS Migration Hub
 * <p>The AWS Migration Hub API methods help to obtain server and application migration status and integrate your resource-specific migration tool by providing a programmatic interface to Migration Hub.</p> <p>Remember that you must set your AWS Migration Hub home region before you call any of these APIs, or a <code>HomeRegionNotSetException</code> error will be returned. Also, you must make the API calls while in your home region.</p>
 *
 * The version of the OpenAPI document: 2017-05-31
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.ResourceAttributeType;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * &lt;p&gt;Attribute associated with a resource.&lt;/p&gt; &lt;p&gt;Note the corresponding format required per type listed below:&lt;/p&gt; &lt;dl&gt; &lt;dt&gt;IPV4&lt;/dt&gt; &lt;dd&gt; &lt;p&gt; &lt;code&gt;x.x.x.x&lt;/code&gt; &lt;/p&gt; &lt;p&gt; &lt;i&gt;where x is an integer in the range [0,255]&lt;/i&gt; &lt;/p&gt; &lt;/dd&gt; &lt;dt&gt;IPV6&lt;/dt&gt; &lt;dd&gt; &lt;p&gt; &lt;code&gt;y : y : y : y : y : y : y : y&lt;/code&gt; &lt;/p&gt; &lt;p&gt; &lt;i&gt;where y is a hexadecimal between 0 and FFFF. [0, FFFF]&lt;/i&gt; &lt;/p&gt; &lt;/dd&gt; &lt;dt&gt;MAC_ADDRESS&lt;/dt&gt; &lt;dd&gt; &lt;p&gt; &lt;code&gt;^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$&lt;/code&gt; &lt;/p&gt; &lt;/dd&gt; &lt;dt&gt;FQDN&lt;/dt&gt; &lt;dd&gt; &lt;p&gt; &lt;code&gt;^[^&amp;lt;&amp;gt;{}\\\\\\/?,&#x3D;\\\\p{Cntrl}]{1,256}$&lt;/code&gt; &lt;/p&gt; &lt;/dd&gt; &lt;/dl&gt;
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:02:31.467047+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class ResourceAttribute {
  public static final String SERIALIZED_NAME_TYPE = "Type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nonnull
  private ResourceAttributeType type;

  public static final String SERIALIZED_NAME_VALUE = "Value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  @javax.annotation.Nonnull
  private String value;

  public ResourceAttribute() {
  }

  public ResourceAttribute type(@javax.annotation.Nonnull ResourceAttributeType type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  public ResourceAttributeType getType() {
    return type;
  }

  public void setType(@javax.annotation.Nonnull ResourceAttributeType type) {
    this.type = type;
  }


  public ResourceAttribute value(@javax.annotation.Nonnull String value) {
    this.value = value;
    return this;
  }

  /**
   * Get value
   * @return value
   */
  @javax.annotation.Nonnull
  public String getValue() {
    return value;
  }

  public void setValue(@javax.annotation.Nonnull String value) {
    this.value = value;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResourceAttribute resourceAttribute = (ResourceAttribute) o;
    return Objects.equals(this.type, resourceAttribute.type) &&
        Objects.equals(this.value, resourceAttribute.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResourceAttribute {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("Type");
    openapiFields.add("Value");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("Type");
    openapiRequiredFields.add("Value");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ResourceAttribute
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ResourceAttribute.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ResourceAttribute is not found in the empty JSON string", ResourceAttribute.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ResourceAttribute.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ResourceAttribute` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ResourceAttribute.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `Type`
      ResourceAttributeType.validateJsonElement(jsonObj.get("Type"));
      // validate the required field `Value`
      String.validateJsonElement(jsonObj.get("Value"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ResourceAttribute.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ResourceAttribute' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ResourceAttribute> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ResourceAttribute.class));

       return (TypeAdapter<T>) new TypeAdapter<ResourceAttribute>() {
           @Override
           public void write(JsonWriter out, ResourceAttribute value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ResourceAttribute read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ResourceAttribute given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ResourceAttribute
   * @throws IOException if the JSON string is invalid with respect to ResourceAttribute
   */
  public static ResourceAttribute fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ResourceAttribute.class);
  }

  /**
   * Convert an instance of ResourceAttribute to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

