/*
 * AWS Migration Hub
 * <p>The AWS Migration Hub API methods help to obtain server and application migration status and integrate your resource-specific migration tool by providing a programmatic interface to Migration Hub.</p> <p>Remember that you must set your AWS Migration Hub home region before you call any of these APIs, or a <code>HomeRegionNotSetException</code> error will be returned. Also, you must make the API calls while in your home region.</p>
 *
 * The version of the OpenAPI document: 2017-05-31
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.AssociateCreatedArtifactRequest;
import org.openapitools.client.model.AssociateDiscoveredResourceRequest;
import org.openapitools.client.model.CreateProgressUpdateStreamRequest;
import org.openapitools.client.model.DeleteProgressUpdateStreamRequest;
import org.openapitools.client.model.DescribeApplicationStateRequest;
import org.openapitools.client.model.DescribeApplicationStateResult;
import org.openapitools.client.model.DescribeMigrationTaskRequest;
import org.openapitools.client.model.DescribeMigrationTaskResult;
import org.openapitools.client.model.DisassociateCreatedArtifactRequest;
import org.openapitools.client.model.DisassociateDiscoveredResourceRequest;
import org.openapitools.client.model.ImportMigrationTaskRequest;
import org.openapitools.client.model.ListApplicationStatesRequest;
import org.openapitools.client.model.ListApplicationStatesResult;
import org.openapitools.client.model.ListCreatedArtifactsRequest;
import org.openapitools.client.model.ListCreatedArtifactsResult;
import org.openapitools.client.model.ListDiscoveredResourcesRequest;
import org.openapitools.client.model.ListDiscoveredResourcesResult;
import org.openapitools.client.model.ListMigrationTasksRequest;
import org.openapitools.client.model.ListMigrationTasksResult;
import org.openapitools.client.model.ListProgressUpdateStreamsRequest;
import org.openapitools.client.model.ListProgressUpdateStreamsResult;
import org.openapitools.client.model.NotifyApplicationStateRequest;
import org.openapitools.client.model.NotifyMigrationTaskStateRequest;
import org.openapitools.client.model.PutResourceAttributesRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Disabled
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * &lt;p&gt;Associates a created artifact of an AWS cloud resource, the target receiving the migration, with the migration task performed by a migration tool. This API has the following traits:&lt;/p&gt; &lt;ul&gt; &lt;li&gt; &lt;p&gt;Migration tools can call the &lt;code&gt;AssociateCreatedArtifact&lt;/code&gt; operation to indicate which AWS artifact is associated with a migration task.&lt;/p&gt; &lt;/li&gt; &lt;li&gt; &lt;p&gt;The created artifact name must be provided in ARN (Amazon Resource Name) format which will contain information about type and region; for example: &lt;code&gt;arn:aws:ec2:us-east-1:488216288981:image/ami-6d0ba87b&lt;/code&gt;.&lt;/p&gt; &lt;/li&gt; &lt;li&gt; &lt;p&gt;Examples of the AWS resource behind the created artifact are, AMI&#39;s, EC2 instance, or DMS endpoint, etc.&lt;/p&gt; &lt;/li&gt; &lt;/ul&gt;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void associateCreatedArtifactTest() throws ApiException {
        String xAmzTarget = null;
        AssociateCreatedArtifactRequest associateCreatedArtifactRequest = null;
        String xAmzContentSha256 = null;
        String xAmzDate = null;
        String xAmzAlgorithm = null;
        String xAmzCredential = null;
        String xAmzSecurityToken = null;
        String xAmzSignature = null;
        String xAmzSignedHeaders = null;
        Object response = api.associateCreatedArtifact(xAmzTarget, associateCreatedArtifactRequest, xAmzContentSha256, xAmzDate, xAmzAlgorithm, xAmzCredential, xAmzSecurityToken, xAmzSignature, xAmzSignedHeaders);
        // TODO: test validations
    }

    /**
     * Associates a discovered resource ID from Application Discovery Service with a migration task.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void associateDiscoveredResourceTest() throws ApiException {
        String xAmzTarget = null;
        AssociateDiscoveredResourceRequest associateDiscoveredResourceRequest = null;
        String xAmzContentSha256 = null;
        String xAmzDate = null;
        String xAmzAlgorithm = null;
        String xAmzCredential = null;
        String xAmzSecurityToken = null;
        String xAmzSignature = null;
        String xAmzSignedHeaders = null;
        Object response = api.associateDiscoveredResource(xAmzTarget, associateDiscoveredResourceRequest, xAmzContentSha256, xAmzDate, xAmzAlgorithm, xAmzCredential, xAmzSecurityToken, xAmzSignature, xAmzSignedHeaders);
        // TODO: test validations
    }

    /**
     * Creates a progress update stream which is an AWS resource used for access control as well as a namespace for migration task names that is implicitly linked to your AWS account. It must uniquely identify the migration tool as it is used for all updates made by the tool; however, it does not need to be unique for each AWS account because it is scoped to the AWS account.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createProgressUpdateStreamTest() throws ApiException {
        String xAmzTarget = null;
        CreateProgressUpdateStreamRequest createProgressUpdateStreamRequest = null;
        String xAmzContentSha256 = null;
        String xAmzDate = null;
        String xAmzAlgorithm = null;
        String xAmzCredential = null;
        String xAmzSecurityToken = null;
        String xAmzSignature = null;
        String xAmzSignedHeaders = null;
        Object response = api.createProgressUpdateStream(xAmzTarget, createProgressUpdateStreamRequest, xAmzContentSha256, xAmzDate, xAmzAlgorithm, xAmzCredential, xAmzSecurityToken, xAmzSignature, xAmzSignedHeaders);
        // TODO: test validations
    }

    /**
     * &lt;p&gt;Deletes a progress update stream, including all of its tasks, which was previously created as an AWS resource used for access control. This API has the following traits:&lt;/p&gt; &lt;ul&gt; &lt;li&gt; &lt;p&gt;The only parameter needed for &lt;code&gt;DeleteProgressUpdateStream&lt;/code&gt; is the stream name (same as a &lt;code&gt;CreateProgressUpdateStream&lt;/code&gt; call).&lt;/p&gt; &lt;/li&gt; &lt;li&gt; &lt;p&gt;The call will return, and a background process will asynchronously delete the stream and all of its resources (tasks, associated resources, resource attributes, created artifacts).&lt;/p&gt; &lt;/li&gt; &lt;li&gt; &lt;p&gt;If the stream takes time to be deleted, it might still show up on a &lt;code&gt;ListProgressUpdateStreams&lt;/code&gt; call.&lt;/p&gt; &lt;/li&gt; &lt;li&gt; &lt;p&gt; &lt;code&gt;CreateProgressUpdateStream&lt;/code&gt;, &lt;code&gt;ImportMigrationTask&lt;/code&gt;, &lt;code&gt;NotifyMigrationTaskState&lt;/code&gt;, and all Associate[*] APIs related to the tasks belonging to the stream will throw \&quot;InvalidInputException\&quot; if the stream of the same name is in the process of being deleted.&lt;/p&gt; &lt;/li&gt; &lt;li&gt; &lt;p&gt;Once the stream and all of its resources are deleted, &lt;code&gt;CreateProgressUpdateStream&lt;/code&gt; for a stream of the same name will succeed, and that stream will be an entirely new logical resource (without any resources associated with the old stream).&lt;/p&gt; &lt;/li&gt; &lt;/ul&gt;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteProgressUpdateStreamTest() throws ApiException {
        String xAmzTarget = null;
        DeleteProgressUpdateStreamRequest deleteProgressUpdateStreamRequest = null;
        String xAmzContentSha256 = null;
        String xAmzDate = null;
        String xAmzAlgorithm = null;
        String xAmzCredential = null;
        String xAmzSecurityToken = null;
        String xAmzSignature = null;
        String xAmzSignedHeaders = null;
        Object response = api.deleteProgressUpdateStream(xAmzTarget, deleteProgressUpdateStreamRequest, xAmzContentSha256, xAmzDate, xAmzAlgorithm, xAmzCredential, xAmzSecurityToken, xAmzSignature, xAmzSignedHeaders);
        // TODO: test validations
    }

    /**
     * Gets the migration status of an application.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void describeApplicationStateTest() throws ApiException {
        String xAmzTarget = null;
        DescribeApplicationStateRequest describeApplicationStateRequest = null;
        String xAmzContentSha256 = null;
        String xAmzDate = null;
        String xAmzAlgorithm = null;
        String xAmzCredential = null;
        String xAmzSecurityToken = null;
        String xAmzSignature = null;
        String xAmzSignedHeaders = null;
        DescribeApplicationStateResult response = api.describeApplicationState(xAmzTarget, describeApplicationStateRequest, xAmzContentSha256, xAmzDate, xAmzAlgorithm, xAmzCredential, xAmzSecurityToken, xAmzSignature, xAmzSignedHeaders);
        // TODO: test validations
    }

    /**
     * Retrieves a list of all attributes associated with a specific migration task.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void describeMigrationTaskTest() throws ApiException {
        String xAmzTarget = null;
        DescribeMigrationTaskRequest describeMigrationTaskRequest = null;
        String xAmzContentSha256 = null;
        String xAmzDate = null;
        String xAmzAlgorithm = null;
        String xAmzCredential = null;
        String xAmzSecurityToken = null;
        String xAmzSignature = null;
        String xAmzSignedHeaders = null;
        DescribeMigrationTaskResult response = api.describeMigrationTask(xAmzTarget, describeMigrationTaskRequest, xAmzContentSha256, xAmzDate, xAmzAlgorithm, xAmzCredential, xAmzSecurityToken, xAmzSignature, xAmzSignedHeaders);
        // TODO: test validations
    }

    /**
     * &lt;p&gt;Disassociates a created artifact of an AWS resource with a migration task performed by a migration tool that was previously associated. This API has the following traits:&lt;/p&gt; &lt;ul&gt; &lt;li&gt; &lt;p&gt;A migration user can call the &lt;code&gt;DisassociateCreatedArtifacts&lt;/code&gt; operation to disassociate a created AWS Artifact from a migration task.&lt;/p&gt; &lt;/li&gt; &lt;li&gt; &lt;p&gt;The created artifact name must be provided in ARN (Amazon Resource Name) format which will contain information about type and region; for example: &lt;code&gt;arn:aws:ec2:us-east-1:488216288981:image/ami-6d0ba87b&lt;/code&gt;.&lt;/p&gt; &lt;/li&gt; &lt;li&gt; &lt;p&gt;Examples of the AWS resource behind the created artifact are, AMI&#39;s, EC2 instance, or RDS instance, etc.&lt;/p&gt; &lt;/li&gt; &lt;/ul&gt;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void disassociateCreatedArtifactTest() throws ApiException {
        String xAmzTarget = null;
        DisassociateCreatedArtifactRequest disassociateCreatedArtifactRequest = null;
        String xAmzContentSha256 = null;
        String xAmzDate = null;
        String xAmzAlgorithm = null;
        String xAmzCredential = null;
        String xAmzSecurityToken = null;
        String xAmzSignature = null;
        String xAmzSignedHeaders = null;
        Object response = api.disassociateCreatedArtifact(xAmzTarget, disassociateCreatedArtifactRequest, xAmzContentSha256, xAmzDate, xAmzAlgorithm, xAmzCredential, xAmzSecurityToken, xAmzSignature, xAmzSignedHeaders);
        // TODO: test validations
    }

    /**
     * Disassociate an Application Discovery Service discovered resource from a migration task.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void disassociateDiscoveredResourceTest() throws ApiException {
        String xAmzTarget = null;
        DisassociateDiscoveredResourceRequest disassociateDiscoveredResourceRequest = null;
        String xAmzContentSha256 = null;
        String xAmzDate = null;
        String xAmzAlgorithm = null;
        String xAmzCredential = null;
        String xAmzSecurityToken = null;
        String xAmzSignature = null;
        String xAmzSignedHeaders = null;
        Object response = api.disassociateDiscoveredResource(xAmzTarget, disassociateDiscoveredResourceRequest, xAmzContentSha256, xAmzDate, xAmzAlgorithm, xAmzCredential, xAmzSecurityToken, xAmzSignature, xAmzSignedHeaders);
        // TODO: test validations
    }

    /**
     * &lt;p&gt;Registers a new migration task which represents a server, database, etc., being migrated to AWS by a migration tool.&lt;/p&gt; &lt;p&gt;This API is a prerequisite to calling the &lt;code&gt;NotifyMigrationTaskState&lt;/code&gt; API as the migration tool must first register the migration task with Migration Hub.&lt;/p&gt;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void importMigrationTaskTest() throws ApiException {
        String xAmzTarget = null;
        ImportMigrationTaskRequest importMigrationTaskRequest = null;
        String xAmzContentSha256 = null;
        String xAmzDate = null;
        String xAmzAlgorithm = null;
        String xAmzCredential = null;
        String xAmzSecurityToken = null;
        String xAmzSignature = null;
        String xAmzSignedHeaders = null;
        Object response = api.importMigrationTask(xAmzTarget, importMigrationTaskRequest, xAmzContentSha256, xAmzDate, xAmzAlgorithm, xAmzCredential, xAmzSecurityToken, xAmzSignature, xAmzSignedHeaders);
        // TODO: test validations
    }

    /**
     * Lists all the migration statuses for your applications. If you use the optional &lt;code&gt;ApplicationIds&lt;/code&gt; parameter, only the migration statuses for those applications will be returned.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listApplicationStatesTest() throws ApiException {
        String xAmzTarget = null;
        ListApplicationStatesRequest listApplicationStatesRequest = null;
        String xAmzContentSha256 = null;
        String xAmzDate = null;
        String xAmzAlgorithm = null;
        String xAmzCredential = null;
        String xAmzSecurityToken = null;
        String xAmzSignature = null;
        String xAmzSignedHeaders = null;
        String maxResults = null;
        String nextToken = null;
        ListApplicationStatesResult response = api.listApplicationStates(xAmzTarget, listApplicationStatesRequest, xAmzContentSha256, xAmzDate, xAmzAlgorithm, xAmzCredential, xAmzSecurityToken, xAmzSignature, xAmzSignedHeaders, maxResults, nextToken);
        // TODO: test validations
    }

    /**
     * &lt;p&gt;Lists the created artifacts attached to a given migration task in an update stream. This API has the following traits:&lt;/p&gt; &lt;ul&gt; &lt;li&gt; &lt;p&gt;Gets the list of the created artifacts while migration is taking place.&lt;/p&gt; &lt;/li&gt; &lt;li&gt; &lt;p&gt;Shows the artifacts created by the migration tool that was associated by the &lt;code&gt;AssociateCreatedArtifact&lt;/code&gt; API. &lt;/p&gt; &lt;/li&gt; &lt;li&gt; &lt;p&gt;Lists created artifacts in a paginated interface. &lt;/p&gt; &lt;/li&gt; &lt;/ul&gt;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listCreatedArtifactsTest() throws ApiException {
        String xAmzTarget = null;
        ListCreatedArtifactsRequest listCreatedArtifactsRequest = null;
        String xAmzContentSha256 = null;
        String xAmzDate = null;
        String xAmzAlgorithm = null;
        String xAmzCredential = null;
        String xAmzSecurityToken = null;
        String xAmzSignature = null;
        String xAmzSignedHeaders = null;
        String maxResults = null;
        String nextToken = null;
        ListCreatedArtifactsResult response = api.listCreatedArtifacts(xAmzTarget, listCreatedArtifactsRequest, xAmzContentSha256, xAmzDate, xAmzAlgorithm, xAmzCredential, xAmzSecurityToken, xAmzSignature, xAmzSignedHeaders, maxResults, nextToken);
        // TODO: test validations
    }

    /**
     * Lists discovered resources associated with the given &lt;code&gt;MigrationTask&lt;/code&gt;.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listDiscoveredResourcesTest() throws ApiException {
        String xAmzTarget = null;
        ListDiscoveredResourcesRequest listDiscoveredResourcesRequest = null;
        String xAmzContentSha256 = null;
        String xAmzDate = null;
        String xAmzAlgorithm = null;
        String xAmzCredential = null;
        String xAmzSecurityToken = null;
        String xAmzSignature = null;
        String xAmzSignedHeaders = null;
        String maxResults = null;
        String nextToken = null;
        ListDiscoveredResourcesResult response = api.listDiscoveredResources(xAmzTarget, listDiscoveredResourcesRequest, xAmzContentSha256, xAmzDate, xAmzAlgorithm, xAmzCredential, xAmzSecurityToken, xAmzSignature, xAmzSignedHeaders, maxResults, nextToken);
        // TODO: test validations
    }

    /**
     * &lt;p&gt;Lists all, or filtered by resource name, migration tasks associated with the user account making this call. This API has the following traits:&lt;/p&gt; &lt;ul&gt; &lt;li&gt; &lt;p&gt;Can show a summary list of the most recent migration tasks.&lt;/p&gt; &lt;/li&gt; &lt;li&gt; &lt;p&gt;Can show a summary list of migration tasks associated with a given discovered resource.&lt;/p&gt; &lt;/li&gt; &lt;li&gt; &lt;p&gt;Lists migration tasks in a paginated interface.&lt;/p&gt; &lt;/li&gt; &lt;/ul&gt;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listMigrationTasksTest() throws ApiException {
        String xAmzTarget = null;
        ListMigrationTasksRequest listMigrationTasksRequest = null;
        String xAmzContentSha256 = null;
        String xAmzDate = null;
        String xAmzAlgorithm = null;
        String xAmzCredential = null;
        String xAmzSecurityToken = null;
        String xAmzSignature = null;
        String xAmzSignedHeaders = null;
        String maxResults = null;
        String nextToken = null;
        ListMigrationTasksResult response = api.listMigrationTasks(xAmzTarget, listMigrationTasksRequest, xAmzContentSha256, xAmzDate, xAmzAlgorithm, xAmzCredential, xAmzSecurityToken, xAmzSignature, xAmzSignedHeaders, maxResults, nextToken);
        // TODO: test validations
    }

    /**
     * Lists progress update streams associated with the user account making this call.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listProgressUpdateStreamsTest() throws ApiException {
        String xAmzTarget = null;
        ListProgressUpdateStreamsRequest listProgressUpdateStreamsRequest = null;
        String xAmzContentSha256 = null;
        String xAmzDate = null;
        String xAmzAlgorithm = null;
        String xAmzCredential = null;
        String xAmzSecurityToken = null;
        String xAmzSignature = null;
        String xAmzSignedHeaders = null;
        String maxResults = null;
        String nextToken = null;
        ListProgressUpdateStreamsResult response = api.listProgressUpdateStreams(xAmzTarget, listProgressUpdateStreamsRequest, xAmzContentSha256, xAmzDate, xAmzAlgorithm, xAmzCredential, xAmzSecurityToken, xAmzSignature, xAmzSignedHeaders, maxResults, nextToken);
        // TODO: test validations
    }

    /**
     * Sets the migration state of an application. For a given application identified by the value passed to &lt;code&gt;ApplicationId&lt;/code&gt;, its status is set or updated by passing one of three values to &lt;code&gt;Status&lt;/code&gt;: &lt;code&gt;NOT_STARTED | IN_PROGRESS | COMPLETED&lt;/code&gt;.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void notifyApplicationStateTest() throws ApiException {
        String xAmzTarget = null;
        NotifyApplicationStateRequest notifyApplicationStateRequest = null;
        String xAmzContentSha256 = null;
        String xAmzDate = null;
        String xAmzAlgorithm = null;
        String xAmzCredential = null;
        String xAmzSecurityToken = null;
        String xAmzSignature = null;
        String xAmzSignedHeaders = null;
        Object response = api.notifyApplicationState(xAmzTarget, notifyApplicationStateRequest, xAmzContentSha256, xAmzDate, xAmzAlgorithm, xAmzCredential, xAmzSecurityToken, xAmzSignature, xAmzSignedHeaders);
        // TODO: test validations
    }

    /**
     * &lt;p&gt;Notifies Migration Hub of the current status, progress, or other detail regarding a migration task. This API has the following traits:&lt;/p&gt; &lt;ul&gt; &lt;li&gt; &lt;p&gt;Migration tools will call the &lt;code&gt;NotifyMigrationTaskState&lt;/code&gt; API to share the latest progress and status.&lt;/p&gt; &lt;/li&gt; &lt;li&gt; &lt;p&gt; &lt;code&gt;MigrationTaskName&lt;/code&gt; is used for addressing updates to the correct target.&lt;/p&gt; &lt;/li&gt; &lt;li&gt; &lt;p&gt; &lt;code&gt;ProgressUpdateStream&lt;/code&gt; is used for access control and to provide a namespace for each migration tool.&lt;/p&gt; &lt;/li&gt; &lt;/ul&gt;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void notifyMigrationTaskStateTest() throws ApiException {
        String xAmzTarget = null;
        NotifyMigrationTaskStateRequest notifyMigrationTaskStateRequest = null;
        String xAmzContentSha256 = null;
        String xAmzDate = null;
        String xAmzAlgorithm = null;
        String xAmzCredential = null;
        String xAmzSecurityToken = null;
        String xAmzSignature = null;
        String xAmzSignedHeaders = null;
        Object response = api.notifyMigrationTaskState(xAmzTarget, notifyMigrationTaskStateRequest, xAmzContentSha256, xAmzDate, xAmzAlgorithm, xAmzCredential, xAmzSecurityToken, xAmzSignature, xAmzSignedHeaders);
        // TODO: test validations
    }

    /**
     * &lt;p&gt;Provides identifying details of the resource being migrated so that it can be associated in the Application Discovery Service repository. This association occurs asynchronously after &lt;code&gt;PutResourceAttributes&lt;/code&gt; returns.&lt;/p&gt; &lt;important&gt; &lt;ul&gt; &lt;li&gt; &lt;p&gt;Keep in mind that subsequent calls to PutResourceAttributes will override previously stored attributes. For example, if it is first called with a MAC address, but later, it is desired to &lt;i&gt;add&lt;/i&gt; an IP address, it will then be required to call it with &lt;i&gt;both&lt;/i&gt; the IP and MAC addresses to prevent overriding the MAC address.&lt;/p&gt; &lt;/li&gt; &lt;li&gt; &lt;p&gt;Note the instructions regarding the special use case of the &lt;a href&#x3D;\&quot;https://docs.aws.amazon.com/migrationhub/latest/ug/API_PutResourceAttributes.html#migrationhub-PutResourceAttributes-request-ResourceAttributeList\&quot;&gt; &lt;code&gt;ResourceAttributeList&lt;/code&gt; &lt;/a&gt; parameter when specifying any \&quot;VM\&quot; related value.&lt;/p&gt; &lt;/li&gt; &lt;/ul&gt; &lt;/important&gt; &lt;note&gt; &lt;p&gt;Because this is an asynchronous call, it will always return 200, whether an association occurs or not. To confirm if an association was found based on the provided details, call &lt;code&gt;ListDiscoveredResources&lt;/code&gt;.&lt;/p&gt; &lt;/note&gt;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void putResourceAttributesTest() throws ApiException {
        String xAmzTarget = null;
        PutResourceAttributesRequest putResourceAttributesRequest = null;
        String xAmzContentSha256 = null;
        String xAmzDate = null;
        String xAmzAlgorithm = null;
        String xAmzCredential = null;
        String xAmzSecurityToken = null;
        String xAmzSignature = null;
        String xAmzSignedHeaders = null;
        Object response = api.putResourceAttributes(xAmzTarget, putResourceAttributesRequest, xAmzContentSha256, xAmzDate, xAmzAlgorithm, xAmzCredential, xAmzSecurityToken, xAmzSignature, xAmzSignedHeaders);
        // TODO: test validations
    }

}
